# Vanilla Docker Compose for Server and Mongo
version: '3.3'

volumes:
  mongo:

networks:
  default:
    name: crimevision-network
  
services:
  mongo:
    container_name: crimevision-mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongo:/data/db

  crimevision-server:
    container_name: crimevision-server
    ports:
      - ${CRIMEVISION_NETWORK_INTERFACE}:3000:3000
    environment:
      - "MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo"
    build: .
    links:
      - mongo
